#!/bin/bash

#This script automates the configuration of the gpg agent to cache passphrases.
#This script was used and tested on a CLI server.
#You can use it on a server to automate a task that requires interaction with GPG.
#We assume here that the private/public key pair has been generated and that the folder ~/.gnupg exists.
#Tested with gpg-agent version 2.2.12

set -e

#Check run at no superuser

if [[ "$EUID" -eq 0 ]]; then
	echo -e "Run this script as no root"
	exit 1
fi

#Export GPG_TTY variable in ~/.bashrc

for users in $(awk -F: '/\/home/ {printf "%s:%s\n",$1,$3}' /etc/passwd | cut -d: -f1)
do
cat << EOF >> /home/$users/.bashrc
#GPG agent
GPG_TTY=$(tty)
export GPG_TTY
EOF
done

#Configure agent options use

for users in $(awk -F: '/\/home/ {printf "%s:%s\n",$1,$3}' /etc/passwd | cut -d: -f1)
do
mkdir /home/$users/.gnupg || true
touch /home/$users/.gnupg/gpg-agent.conf
cat << EOF > /home/$users/.gnupg/gpg-agent.conf
default-cache-ttl 315360000
max-cache-ttl 315360000
pinentry-program /usr/bin/pinentry-curses
allow-preset-passphrase
pinentry-timeout 0
EOF
done

#default-cache-ttl sets the default cache phrase length for the passphrase (in seconds, here 10 years)
#max-cache-ttl sets the maximum cache phrase length for the passphrase (in seconds, here 10 years)
#pinentry-program defines the software to use to enter the passphrase
#allow-preset-passphrase reads the previously used stdin entry
#pinentry-timeout 0 to disable timeout in pintentry

for users in $(awk -F: '/\/home/ {printf "%s:%s\n",$1,$3}' /etc/passwd | cut -d: -f1)
do
cat << EOF > /home/$users/.gnupg/gpg.conf
use-agent
EOF
done

#See : https://www.gnupg.org/documentation/manuals/gnupg/Agent-Configuration.html#Agent-Configuration
#For details for gpg-agent.conf gpg.conf trustlist.txt files

#Create script to launch and stop gpg-agent

cat << EOF > /opt/gpg-agent
#!/bin/bash

if [[ "$EUID" -eq "0" ]]; then
	echo "Run this script as non root"
	exit 1
fi

function start() {
rm /run/user/*/gnupg/* || true
gpg-agent --daemon
}

function stop() {
rm /run/user/*/gnupg/* || true
}

function explain() {
	echo "Launch script this with argument start or stop."
}

case $1 in
	start)
		start
	;;
	stop)
		stop
	;;
	*)
	explain
	;;
esac
EOF

chmod 0755 /opt/gpg-agent
chown user:user /opt/gpg-agent

#Each time the system is restarted, you must manually launch the command /opt/gpg-agent start
#Daemonising it or putting a crontab will not work.

#Once this configuration is done, enter your passphrase and disconnect from your SSH session for 10 minutes.
#Rerun a command requiring interaction with GPG, if the phrase is not asked again, your configuration is functional.
