#!/bin/bash

if [[ "$EUID" -eq "0" ]]; then
	echo "Run this script as non root"
	exit 1
fi

function start() {
rm /run/user/*/gnupg/* || true
gpg-agent --daemon
}

function stop() {
rm /run/user/*/gnupg/* || true
}

function explain() {
	echo "Launch script this with argument start or stop."
}

case $1 in
	start)
		start
	;;
	stop)
		stop
	;;
	*)
	explain
	;;
esac
