#!/bin/bash

set -e

if [[ "$EUID" -eq "0" ]]; then
	echo "Run this script as non root"
	exit 1
fi

function start() {
for users in $(awk -F: '/\/home/ {printf "%s:%s\n",$1,$3}' /etc/passwd | cut -d: -f1)
do
rm -f /home/$users/S.* || true
done
rm -f /run/user/*/gnupg/S.* || true
gpg-agent --daemon
}

function stop() {
gpgconf --kill gpg-agent
}

function explain() {
	echo "Launch script this with argument start or stop."
}

case $1 in
	start)
		start
	;;
	stop)
		stop
	;;
	*)
	explain
	;;
esac
